### PR TITLE
Json type

### PR DESCRIPTION
**Pull request by fuhrysteve**

### CODE REVIEW

**Comment by fuhrysteve** [comment]
This seems to work:


```python
(staffknex)[fuhrysteve@fuhrysteve-ThinkPad-W520:OnShift/bazman]$ tg-admin -c steve.cfg shell                                                                                                  (02-26 16:22)

In [1]: v2org = V2organization.by_abbr('SVCH')

In [2]: v2org.signals

In [3]: v2org = V2organization.by_abbr('SVCH')

In [4]: from bazman import model

In [5]: v2org.signals = {'foo':'bar'}

In [6]: model.hub.commit()

In [7]: Do you wish to commit your database changes? [yes]
Could not get variable session.flush() from raw_input

Do you really want to exit ([y]/n)? 
(staffknex)[fuhrysteve@fuhrysteve-ThinkPad-W520:OnShift/bazman]$ tg-admin -c steve.cfg shell                                                                                                  (02-26 16:24)

In [1]: v2org = V2organization.by_abbr('SVCH')

In [2]: v2org.signals
Out[2]: {u'foo': u'bar'}

```

**Comment by fuhrysteve** [comment]
This is the only change to the above `V2organization` class

```python
signals = JSONCol(default=None)
```

**Comment by craigmichaelmartin** [comment]
yes yes yes!

**Comment by lieutdan13** [comment]
@fuhrysteve @EricWorkman we will need this to start using the json field types.

**Comment by m-butterfield** [comment]
:monkey:

**Comment by EricWorkman** [comment]
Butterfield!

**Comment by evanstern** [comment]
oO

**Comment by EricWorkman** [comment]
Evan!

**Pull request merged**
